version: '2'
services:

  nginx:
    build: ./nginx
    volumes:
       - ./src:/src
       - /static:/static
       - /media:/media
    depends_on:
      - core
    links:
      - core
    ports:
      - "8000:8000"

  core:
    build: ./am-core
    command: bash -c "python manage.py collectstatic --noinput --settings=settings.dev && python manage.py migrate --fake --settings=settings.dev && uwsgi --ini docker/uwsgi.ini && sleep 365d"
    volumes:
       - ./src:/src
       - /static:/static
       - /media:/media
    links:
      - db
    expose:
      - "8081"

  node:
    build: ./am-static
    volumes:
       - ./src:/src
       - /static:/static
       - /media:/media

  db:
     build: ./configs/db
