version: '2'
services:
  db:
    image: postgres

  nginx:
    build: ./nginx
    volumes:
       - ./src:/src
       - /static:/static
       - /media:/media
    depends_on:
      - core
    links:
      - core
    ports:
      - "8000:8000"

  core:
    build: ./am-core
    command: bash -c "python manage.py migrate --settings=settings.dev && uwsgi --ini docker/uwsgi.ini && sleep 365d"
    volumes:
       - ./am-core:/am-core
       - /static:/static
       - /media:/media
    links:
      - db
    expose:
      - "8081"

  node:
    build: ./am-static
    command: bash -c "npm run watch && sleep 365d"
    volumes:
       - ./am-static:/am-static
       - /static:/static
       - /media:/media
