version: '3.9'
services:
  db:
    image: postgres:15.1-alpine
    container_name: am-db
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - am.env

  nginx:
    build:
      context: ./nginx
      args:
        - NGINX_CONF=nginx.conf
    container_name: am-nginx
    volumes:
      - ./src:/src
      - static:/static
      - media:/media
    env_file:
      - am.env
    depends_on:
      - core
    links:
      - core
    ports:
      - "8000:8000"

  core:
    build: ./am-core
    command: /bin/sh -c "python manage.py collectstatic --noinput --settings=settings.dev && python manage.py migrate --settings=settings.dev && python manage.py runserver 0.0.0.0:8081 --settings=settings.dev"
    container_name: am-core
    volumes:
      - ./am-core:/am-core
      - static:/static
      - media:/media
    env_file:
      - am.env
    links:
      - db
    depends_on:
      - db
    expose:
      - "8081"

  front:
    build: ./am-front
    command: /bin/sh -c "sleep 1d;"
    container_name: am-front
    links:
      - nginx
    volumes:
      - ./am-front:/app
      - static:/static


volumes:
  dbdata:
  static:
  media:
