version: '2'
services:

  nginx:
    build: ./nginx
    volumes:
        - .:/usr/src/app
    links:
      - core
    ports:
      - "8000:8000"

  core:
    build: ./am-core
    volumes:
       - ./am-core:/usr/src/app
    links:
      - db
    expose:
      - "8081"

  db:
     image: postgres