version: '2'
services:
  db:
    image: postgres:9.6.9-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - am.env

  nginx:
    build:
      context: ./nginx
      args:
        - NGINX_CONF=nginx.conf
    volumes:
       - ./src:/src
       - ./am-core/static:/static
       - ./am-core/media:/media
    env_file:
      - am.env
    depends_on:
      - core
    links:
      - core
    ports:
      - "8000:8000"

  core:
    build: ./am-core
    command: /bin/sh -c "python manage.py collectstatic --noinput --settings=settings.dev && python manage.py migrate --settings=settings.dev && uwsgi --ini docker/uwsgi.ini"
    volumes:
       - ./am-core:/am-core
       - ./am-core/static:/static
       - ./am-core/media:/media
    env_file:
      - am.env
    links:
      - db
    depends_on:
      - db
    expose:
      - "8081"

#  front:
#    build: ./am-front
#    command: /bin/sh -c "npm run dev"
#    # command: /bin/sh -c "npm run build && npm run serve"
#    volumes:
#      - ./am-front:/app
#    ports:
#      - 8282:3000
#      - 8383:9000
#    links:
#      - nginx
#
#  node:
#    build: ./am-static
#    command: /bin/sh -c "sleep 365d"
#    volumes:
#       - ./am-static:/am-static
#       - ./am-core/static:/static
#       - ./am-core/media:/media
