/var/log/nginx/traffic.log /var/log/nginx/application-error.log {
    daily
    rotate 60
    maxage 60
    dateext
    dateyesterday
    dateformat -%Y-%m-%d
    compress
    delaycompress
    missingok
    notifempty
    create 0640 root nginx
    sharedscripts
    postrotate
        /usr/sbin/nginx -s reopen
    endscript
}
