worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    resolver 127.0.0.11 valid=10s ipv6=off;

    gzip on;
    gzip_disable "msie6";
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_http_version 1.1;
    gzip_min_length 256;
    gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript application/vnd.ms-fontobject application/x-font-ttf font/opentype image/svg+xml image/x-icon image/jpeg image/png;

    server {
        listen 8000 default_server;
        server_name localhost nginx agromega.in.ua www.agromega.in.ua;
        charset utf-8;
        client_max_body_size 75M;

        error_log /var/log/nginx/error.log;
        access_log /var/log/nginx/access.log;

        location /media/ {
            alias /var/www/media/;
            try_files $uri $uri/ =404;
        }

        location /imgproxy/ {
            set $imgproxy_upstream http://imgproxy:8080;
            rewrite ^/imgproxy/(.*) /$1 break;
            proxy_pass $imgproxy_upstream;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /static/ {
            alias /static/;
            try_files $uri $uri/ =404;
        }

        location = /forum {
            return 302 /forum/;
        }

        location /forum/media/ {
            alias /forum-media/;
            try_files $uri $uri/ =404;
        }

        location /forum/static/ {
            alias /static/;
            try_files $uri $uri/ =404;
        }

        location /forum/ {
            set $forum_upstream http://am-forum-instance:8082;
            rewrite ^/forum/(.*)$ /$1 break;
            proxy_pass $forum_upstream;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Script-Name /forum;
        }

        location / {
            set $core_upstream http://am-core:8081;
            proxy_pass $core_upstream;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
