# Generated by Django 5.2.14 on 2026-07-11 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spirit_comment', '0005_alter_comment_id'),
        ('spirit_topic', '0004_alter_topic_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('kind', models.CharField(choices=[('guide', 'Практичний посібник'), ('ranking', 'Добірка або рейтинг'), ('expert', 'Експертний матеріал'), ('experience', 'Особистий досвід'), ('editorial', 'Матеріал редакції')], default='experience', max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('in_review', 'На розгляді'), ('changes_requested', 'Потрібні зміни'), ('published', 'Опубліковано'), ('rejected', 'Відхилено'), ('archived', 'В архіві')], db_index=True, default='draft', max_length=24)),
                ('excerpt', models.TextField(max_length=500)),
                ('body', models.TextField()),
                ('body_html', models.TextField(editable=False)),
                ('cover', models.ImageField(blank=True, upload_to='publications/covers/%Y/%m/')),
                ('cover_alt', models.CharField(blank=True, max_length=240)),
                ('editorial_notes', models.TextField(blank=True)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('is_editorial', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('disclosure', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to=settings.AUTH_USER_MODEL)),
                ('body_comment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='publication_body', to='spirit_comment.comment')),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='publication', to='spirit_topic.topic')),
            ],
            options={
                'ordering': ('-published_at', '-created_at'),
                'permissions': (('review_publication', 'Can review and publish community publications'),),
            },
        ),
        migrations.CreateModel(
            name='PublicationStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('draft', 'Чернетка'), ('in_review', 'На розгляді'), ('changes_requested', 'Потрібні зміни'), ('published', 'Опубліковано'), ('rejected', 'Відхилено'), ('archived', 'В архіві')], max_length=24)),
                ('to_status', models.CharField(choices=[('draft', 'Чернетка'), ('in_review', 'На розгляді'), ('changes_requested', 'Потрібні зміни'), ('published', 'Опубліковано'), ('rejected', 'Відхилено'), ('archived', 'В архіві')], max_length=24)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='community.publication')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
