# Generated by Django 5.2.14 on 2026-07-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=180, unique=True),
        ),
    ]
